### ISSUE TITLE
read env.yml

### ISSUE THREAD

**Issue by mateo2181** [AmoDinho/prisma2-f1-demo#3]
Hi, I was using the project to copy webpack configuration, and I have a problem in my schema.prisma to read url param.
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

```   

My serverless.yml is:
```
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  environment: ${file(env.yml):${self:provider.stage}}
  . . .
```

and I have my env.yml with:
```
dev:
   DATABASE_URL: "url-dev"
prod:
   DATABASE_URL: "url-prod"
```

I think env("DATABASE_URL") is not working. 

Do you what can be the problem?

Thanks!!
